/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTextosRouteImport } from './routes/_authenticated/textos'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTextosRoute = AuthenticatedTextosRouteImport.update({
  id: '/textos',
  path: '/textos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/links': typeof AuthenticatedLinksRoute
  '/textos': typeof AuthenticatedTextosRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/links': typeof AuthenticatedLinksRoute
  '/textos': typeof AuthenticatedTextosRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/textos': typeof AuthenticatedTextosRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/crm'
    | '/dashboard'
    | '/links'
    | '/textos'
    | '/api/public/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/crm'
    | '/dashboard'
    | '/links'
    | '/textos'
    | '/api/public/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/links'
    | '/_authenticated/textos'
    | '/api/public/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/textos': {
      id: '/_authenticated/textos'
      path: '/textos'
      fullPath: '/textos'
      preLoaderRoute: typeof AuthenticatedTextosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedTextosRoute: typeof AuthenticatedTextosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedTextosRoute: AuthenticatedTextosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
