/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTextosRouteImport } from './routes/_authenticated/textos'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedInstitucionalRouteImport } from './routes/_authenticated/institucional'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFaturamentoRouteImport } from './routes/_authenticated/faturamento'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCuradoriaRouteImport } from './routes/_authenticated/curadoria'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedArquivosRouteImport } from './routes/_authenticated/arquivos'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedCrmRouteRouteImport } from './routes/_authenticated/crm/route'
import { Route as AuthenticatedAcervoRouteRouteImport } from './routes/_authenticated/acervo/route'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm/index'
import { Route as AuthenticatedAcervoIndexRouteImport } from './routes/_authenticated/acervo/index'
import { Route as AuthenticatedCrmIdRouteImport } from './routes/_authenticated/crm/$id'
import { Route as AuthenticatedAcervoPendentesRouteImport } from './routes/_authenticated/acervo/pendentes'
import { Route as AuthenticatedAcervoCollectionRouteImport } from './routes/_authenticated/acervo/$collection'
import { Route as ApiPublicWebhooksHotmartRouteImport } from './routes/api/public/webhooks/hotmart'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'
import { Route as AuthenticatedAcervoItemSlugRouteImport } from './routes/_authenticated/acervo/item/$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTextosRoute = AuthenticatedTextosRouteImport.update({
  id: '/textos',
  path: '/textos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstitucionalRoute =
  AuthenticatedInstitucionalRouteImport.update({
    id: '/institucional',
    path: '/institucional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturamentoRoute =
  AuthenticatedFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuradoriaRoute = AuthenticatedCuradoriaRouteImport.update({
  id: '/curadoria',
  path: '/curadoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArquivosRoute = AuthenticatedArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRouteRoute = AuthenticatedCrmRouteRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcervoRouteRoute =
  AuthenticatedAcervoRouteRouteImport.update({
    id: '/acervo',
    path: '/acervo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRouteRoute,
} as any)
const AuthenticatedAcervoIndexRoute =
  AuthenticatedAcervoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAcervoRouteRoute,
  } as any)
const AuthenticatedCrmIdRoute = AuthenticatedCrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrmRouteRoute,
} as any)
const AuthenticatedAcervoPendentesRoute =
  AuthenticatedAcervoPendentesRouteImport.update({
    id: '/pendentes',
    path: '/pendentes',
    getParentRoute: () => AuthenticatedAcervoRouteRoute,
  } as any)
const AuthenticatedAcervoCollectionRoute =
  AuthenticatedAcervoCollectionRouteImport.update({
    id: '/$collection',
    path: '/$collection',
    getParentRoute: () => AuthenticatedAcervoRouteRoute,
  } as any)
const ApiPublicWebhooksHotmartRoute =
  ApiPublicWebhooksHotmartRouteImport.update({
    id: '/api/public/webhooks/hotmart',
    path: '/api/public/webhooks/hotmart',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcervoItemSlugRoute =
  AuthenticatedAcervoItemSlugRouteImport.update({
    id: '/item/$slug',
    path: '/item/$slug',
    getParentRoute: () => AuthenticatedAcervoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acervo': typeof AuthenticatedAcervoRouteRouteWithChildren
  '/crm': typeof AuthenticatedCrmRouteRouteWithChildren
  '/agenda': typeof AuthenticatedAgendaRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/curadoria': typeof AuthenticatedCuradoriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/institucional': typeof AuthenticatedInstitucionalRoute
  '/links': typeof AuthenticatedLinksRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/textos': typeof AuthenticatedTextosRoute
  '/acervo/$collection': typeof AuthenticatedAcervoCollectionRoute
  '/acervo/pendentes': typeof AuthenticatedAcervoPendentesRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/acervo/': typeof AuthenticatedAcervoIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/acervo/item/$slug': typeof AuthenticatedAcervoItemSlugRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/webhooks/hotmart': typeof ApiPublicWebhooksHotmartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/curadoria': typeof AuthenticatedCuradoriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/institucional': typeof AuthenticatedInstitucionalRoute
  '/links': typeof AuthenticatedLinksRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/textos': typeof AuthenticatedTextosRoute
  '/acervo/$collection': typeof AuthenticatedAcervoCollectionRoute
  '/acervo/pendentes': typeof AuthenticatedAcervoPendentesRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/acervo': typeof AuthenticatedAcervoIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/acervo/item/$slug': typeof AuthenticatedAcervoItemSlugRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/webhooks/hotmart': typeof ApiPublicWebhooksHotmartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/acervo': typeof AuthenticatedAcervoRouteRouteWithChildren
  '/_authenticated/crm': typeof AuthenticatedCrmRouteRouteWithChildren
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/arquivos': typeof AuthenticatedArquivosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/curadoria': typeof AuthenticatedCuradoriaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/faturamento': typeof AuthenticatedFaturamentoRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/institucional': typeof AuthenticatedInstitucionalRoute
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/textos': typeof AuthenticatedTextosRoute
  '/_authenticated/acervo/$collection': typeof AuthenticatedAcervoCollectionRoute
  '/_authenticated/acervo/pendentes': typeof AuthenticatedAcervoPendentesRoute
  '/_authenticated/crm/$id': typeof AuthenticatedCrmIdRoute
  '/_authenticated/acervo/': typeof AuthenticatedAcervoIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/acervo/item/$slug': typeof AuthenticatedAcervoItemSlugRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/webhooks/hotmart': typeof ApiPublicWebhooksHotmartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/acervo'
    | '/crm'
    | '/agenda'
    | '/arquivos'
    | '/configuracoes'
    | '/curadoria'
    | '/dashboard'
    | '/equipe'
    | '/faturamento'
    | '/financeiro'
    | '/institucional'
    | '/links'
    | '/projetos'
    | '/prompts'
    | '/textos'
    | '/acervo/$collection'
    | '/acervo/pendentes'
    | '/crm/$id'
    | '/acervo/'
    | '/crm/'
    | '/acervo/item/$slug'
    | '/api/public/google/callback'
    | '/api/public/webhooks/hotmart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/arquivos'
    | '/configuracoes'
    | '/curadoria'
    | '/dashboard'
    | '/equipe'
    | '/faturamento'
    | '/financeiro'
    | '/institucional'
    | '/links'
    | '/projetos'
    | '/prompts'
    | '/textos'
    | '/acervo/$collection'
    | '/acervo/pendentes'
    | '/crm/$id'
    | '/acervo'
    | '/crm'
    | '/acervo/item/$slug'
    | '/api/public/google/callback'
    | '/api/public/webhooks/hotmart'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/acervo'
    | '/_authenticated/crm'
    | '/_authenticated/agenda'
    | '/_authenticated/arquivos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/curadoria'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/faturamento'
    | '/_authenticated/financeiro'
    | '/_authenticated/institucional'
    | '/_authenticated/links'
    | '/_authenticated/projetos'
    | '/_authenticated/prompts'
    | '/_authenticated/textos'
    | '/_authenticated/acervo/$collection'
    | '/_authenticated/acervo/pendentes'
    | '/_authenticated/crm/$id'
    | '/_authenticated/acervo/'
    | '/_authenticated/crm/'
    | '/_authenticated/acervo/item/$slug'
    | '/api/public/google/callback'
    | '/api/public/webhooks/hotmart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicWebhooksHotmartRoute: typeof ApiPublicWebhooksHotmartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/textos': {
      id: '/_authenticated/textos'
      path: '/textos'
      fullPath: '/textos'
      preLoaderRoute: typeof AuthenticatedTextosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institucional': {
      id: '/_authenticated/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof AuthenticatedInstitucionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturamento': {
      id: '/_authenticated/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof AuthenticatedFaturamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curadoria': {
      id: '/_authenticated/curadoria'
      path: '/curadoria'
      fullPath: '/curadoria'
      preLoaderRoute: typeof AuthenticatedCuradoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arquivos': {
      id: '/_authenticated/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthenticatedArquivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acervo': {
      id: '/_authenticated/acervo'
      path: '/acervo'
      fullPath: '/acervo'
      preLoaderRoute: typeof AuthenticatedAcervoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/acervo/': {
      id: '/_authenticated/acervo/'
      path: '/'
      fullPath: '/acervo/'
      preLoaderRoute: typeof AuthenticatedAcervoIndexRouteImport
      parentRoute: typeof AuthenticatedAcervoRouteRoute
    }
    '/_authenticated/crm/$id': {
      id: '/_authenticated/crm/$id'
      path: '/$id'
      fullPath: '/crm/$id'
      preLoaderRoute: typeof AuthenticatedCrmIdRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/acervo/pendentes': {
      id: '/_authenticated/acervo/pendentes'
      path: '/pendentes'
      fullPath: '/acervo/pendentes'
      preLoaderRoute: typeof AuthenticatedAcervoPendentesRouteImport
      parentRoute: typeof AuthenticatedAcervoRouteRoute
    }
    '/_authenticated/acervo/$collection': {
      id: '/_authenticated/acervo/$collection'
      path: '/$collection'
      fullPath: '/acervo/$collection'
      preLoaderRoute: typeof AuthenticatedAcervoCollectionRouteImport
      parentRoute: typeof AuthenticatedAcervoRouteRoute
    }
    '/api/public/webhooks/hotmart': {
      id: '/api/public/webhooks/hotmart'
      path: '/api/public/webhooks/hotmart'
      fullPath: '/api/public/webhooks/hotmart'
      preLoaderRoute: typeof ApiPublicWebhooksHotmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/acervo/item/$slug': {
      id: '/_authenticated/acervo/item/$slug'
      path: '/item/$slug'
      fullPath: '/acervo/item/$slug'
      preLoaderRoute: typeof AuthenticatedAcervoItemSlugRouteImport
      parentRoute: typeof AuthenticatedAcervoRouteRoute
    }
  }
}

interface AuthenticatedAcervoRouteRouteChildren {
  AuthenticatedAcervoCollectionRoute: typeof AuthenticatedAcervoCollectionRoute
  AuthenticatedAcervoPendentesRoute: typeof AuthenticatedAcervoPendentesRoute
  AuthenticatedAcervoIndexRoute: typeof AuthenticatedAcervoIndexRoute
  AuthenticatedAcervoItemSlugRoute: typeof AuthenticatedAcervoItemSlugRoute
}

const AuthenticatedAcervoRouteRouteChildren: AuthenticatedAcervoRouteRouteChildren =
  {
    AuthenticatedAcervoCollectionRoute: AuthenticatedAcervoCollectionRoute,
    AuthenticatedAcervoPendentesRoute: AuthenticatedAcervoPendentesRoute,
    AuthenticatedAcervoIndexRoute: AuthenticatedAcervoIndexRoute,
    AuthenticatedAcervoItemSlugRoute: AuthenticatedAcervoItemSlugRoute,
  }

const AuthenticatedAcervoRouteRouteWithChildren =
  AuthenticatedAcervoRouteRoute._addFileChildren(
    AuthenticatedAcervoRouteRouteChildren,
  )

interface AuthenticatedCrmRouteRouteChildren {
  AuthenticatedCrmIdRoute: typeof AuthenticatedCrmIdRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedCrmRouteRouteChildren: AuthenticatedCrmRouteRouteChildren = {
  AuthenticatedCrmIdRoute: AuthenticatedCrmIdRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedCrmRouteRouteWithChildren =
  AuthenticatedCrmRouteRoute._addFileChildren(
    AuthenticatedCrmRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcervoRouteRoute: typeof AuthenticatedAcervoRouteRouteWithChildren
  AuthenticatedCrmRouteRoute: typeof AuthenticatedCrmRouteRouteWithChildren
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedArquivosRoute: typeof AuthenticatedArquivosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCuradoriaRoute: typeof AuthenticatedCuradoriaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFaturamentoRoute: typeof AuthenticatedFaturamentoRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedInstitucionalRoute: typeof AuthenticatedInstitucionalRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedTextosRoute: typeof AuthenticatedTextosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcervoRouteRoute: AuthenticatedAcervoRouteRouteWithChildren,
  AuthenticatedCrmRouteRoute: AuthenticatedCrmRouteRouteWithChildren,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedArquivosRoute: AuthenticatedArquivosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCuradoriaRoute: AuthenticatedCuradoriaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFaturamentoRoute: AuthenticatedFaturamentoRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedInstitucionalRoute: AuthenticatedInstitucionalRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedTextosRoute: AuthenticatedTextosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicWebhooksHotmartRoute: ApiPublicWebhooksHotmartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
