/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTextosRouteImport } from './routes/_authenticated/textos'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedInstitucionalRouteImport } from './routes/_authenticated/institucional'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedArquivosRouteImport } from './routes/_authenticated/arquivos'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTextosRoute = AuthenticatedTextosRouteImport.update({
  id: '/textos',
  path: '/textos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstitucionalRoute =
  AuthenticatedInstitucionalRouteImport.update({
    id: '/institucional',
    path: '/institucional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArquivosRoute = AuthenticatedArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/institucional': typeof AuthenticatedInstitucionalRoute
  '/links': typeof AuthenticatedLinksRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/textos': typeof AuthenticatedTextosRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/institucional': typeof AuthenticatedInstitucionalRoute
  '/links': typeof AuthenticatedLinksRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/textos': typeof AuthenticatedTextosRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/arquivos': typeof AuthenticatedArquivosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/institucional': typeof AuthenticatedInstitucionalRoute
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/textos': typeof AuthenticatedTextosRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/arquivos'
    | '/configuracoes'
    | '/crm'
    | '/dashboard'
    | '/equipe'
    | '/financeiro'
    | '/institucional'
    | '/links'
    | '/projetos'
    | '/prompts'
    | '/textos'
    | '/api/public/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/arquivos'
    | '/configuracoes'
    | '/crm'
    | '/dashboard'
    | '/equipe'
    | '/financeiro'
    | '/institucional'
    | '/links'
    | '/projetos'
    | '/prompts'
    | '/textos'
    | '/api/public/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/arquivos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/institucional'
    | '/_authenticated/links'
    | '/_authenticated/projetos'
    | '/_authenticated/prompts'
    | '/_authenticated/textos'
    | '/api/public/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/textos': {
      id: '/_authenticated/textos'
      path: '/textos'
      fullPath: '/textos'
      preLoaderRoute: typeof AuthenticatedTextosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institucional': {
      id: '/_authenticated/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof AuthenticatedInstitucionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arquivos': {
      id: '/_authenticated/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthenticatedArquivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedArquivosRoute: typeof AuthenticatedArquivosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedInstitucionalRoute: typeof AuthenticatedInstitucionalRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedTextosRoute: typeof AuthenticatedTextosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedArquivosRoute: AuthenticatedArquivosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedInstitucionalRoute: AuthenticatedInstitucionalRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedTextosRoute: AuthenticatedTextosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
